
target 'LazyWalker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Alamofire', '~> 4.3'

   pod 'PureLayout', '~> 2.0.5'

   
   pod 'Charts', '~> 3.0.1'
   pod 'RealmSwift', '~> 2.0.2'

end
